Backblaze/b2-sdk-java

core/src/main/java/com/backblaze/b2/util/B2Preconditions.java
core/src/test/java/com/backblaze/b2/util/B2PreconditionsTest.java

tested with new unit test cases.

B2Preconditions: add checkArgumentIsNotNull.

---

httpclient/src/main/java/com/backblaze/b2/client/webApiHttpClient/HttpClientFactoryImpl.java

by default we only support 'https' since that's what production b2
servers require.
exercised locally.

httpClientFactory: optionally support 'http' in the httpClients.

---

core/src/main/java/com/backblaze/b2/client/B2ByteProgressFilteringListener.java
core/src/main/java/com/backblaze/b2/client/B2ContentSourceWithByteProgressListener.java
core/src/main/java/com/backblaze/b2/client/B2LargeFileUploader.java
core/src/main/java/com/backblaze/b2/client/B2PartSpec.java
core/src/main/java/com/backblaze/b2/client/B2StorageClientWebifierImpl.java
core/src/main/java/com/backblaze/b2/client/B2UploadProgressAdapter.java
core/src/main/java/com/backblaze/b2/client/B2UploadProgressUtil.java
core/src/main/java/com/backblaze/b2/client/structures/B2UploadFileRequest.java
core/src/main/java/com/backblaze/b2/client/structures/B2UploadListener.java
core/src/main/java/com/backblaze/b2/client/structures/B2UploadProgress.java
core/src/main/java/com/backblaze/b2/client/structures/B2UploadState.java
core/src/main/java/com/backblaze/b2/util/B2ByteProgressListener.java
core/src/main/java/com/backblaze/b2/util/B2DateTimeUtil.java
core/src/main/java/com/backblaze/b2/util/B2InputStreamWithByteProgressListener.java
core/src/test/java/com/backblaze/b2/client/B2ContentSourceWithByteProgressListenerTest.java
core/src/test/java/com/backblaze/b2/client/B2UploadProgressAdapterTest.java
core/src/test/java/com/backblaze/b2/client/B2UploadProgressUtilTest.java
core/src/test/java/com/backblaze/b2/client/structures/B2UploadProgressTest.java
core/src/test/java/com/backblaze/b2/util/B2InputStreamWithByteProgressListenerTest.java
samples/src/main/java/com/backblaze/b2/sample/B2Sample.java

This adds B2UploadListener and arranges to call it as progress is made on uploading both small files and large files.

Upload progress

---

httpclient/src/main/java/com/backblaze/b2/client/webApiHttpClient/HttpClientFactoryImpl.java

this is based on the recommendation and sample code in
https://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html
ran B2Sample locally in the debugger to watch the thread get created, run, and shutdown.
did a "./gradlew clean build javadoc" for good measure (but the unit tests don't exercise the http client code)

httpClient: add a thread that cleans up idle connections.

---

samples/src/main/java/com/backblaze/b2/sample/B2.java

B2.java: add get_download_authorization

---

core/src/main/java/com/backblaze/b2/client/B2StorageClient.java
core/src/main/java/com/backblaze/b2/client/B2StorageClientImpl.java
core/src/main/java/com/backblaze/b2/client/structures/B2AccountAuthorization.java
core/src/test/java/com/backblaze/b2/client/B2AccountAuthorizationCacheTest.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientImplTest.java
samples/src/main/java/com/backblaze/b2/sample/B2Sample.java

...and invalidateAccountAuthorization().
and test it.
and exercise it in B2Sample.
resolves #14.

b2StorageClient: add getAccountAuthorization().

---

samples/src/main/java/com/backblaze/b2/sample/B2.java

of course, setting them to anything other than '[]' is yields an error
from the servers because the server doesn't support corsRules yet.
tested with '[]' on the command line.
tested with '@/tmp/cors.json' with the file:
* missing (got expected error)
* containing '[]'
* containing malformed json (got expected error)
* containing a properly formed corsRule (got expected error from server)

b2.java: add 'update_bucket_cors_rules' to let users set corsRules.

---

core/src/main/java/com/backblaze/b2/client/structures/B2CorsRule.java
core/src/main/java/com/backblaze/b2/client/structures/B2CreateBucketRequestReal.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientWebifierImplTest.java
core/src/test/java/com/backblaze/b2/client/B2TestHelpers.java

Also added a comment about the difference between
B2CreateBucketRequestReal and B2CreatBucketRequest.

Add corsRulesName to the CorsRule class and fixed test cases.

---

core/src/main/java/com/backblaze/b2/client/B2StorageClient.java
core/src/main/java/com/backblaze/b2/client/B2StorageClientImpl.java
core/src/main/java/com/backblaze/b2/client/structures/B2GetUploadPartUrlRequest.java
core/src/main/java/com/backblaze/b2/client/structures/B2StartLargeFileRequest.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientImplTest.java

they might be useful for someone once b2 supports CORS for uploading
parts of large files.  :)

client: expose startLargeFile and finishLargeFile.

---

httpclient/src/main/java/com/backblaze/b2/client/webApiHttpClient/HttpClientFactoryImpl.java

we compute default the HttpClient user-agent the same way HttpClient
does it and we keep the result as a constant, so that we can prevent
HttpClientBuilder doing that work every time we make an HttpClient.
(we make them and discard them constantly and HttpClient computing
the default is expensive because it opens a resource from its jar
and we'd like to avoid those unnecessary syscalls and unzipping.)
besides, we override the value later.  :)

httpClientFactory: explicitly set the user-agent on the HttpClient

---

core/src/main/java/com/backblaze/b2/client/B2StorageClient.java
core/src/main/java/com/backblaze/b2/client/B2StorageClientImpl.java
core/src/main/java/com/backblaze/b2/client/B2StorageClientWebifier.java
core/src/main/java/com/backblaze/b2/client/B2StorageClientWebifierImpl.java
core/src/main/java/com/backblaze/b2/client/structures/B2GetFileInfoByNameRequest.java
core/src/main/java/com/backblaze/b2/client/webApiClients/B2WebApiClient.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientImplTest.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientWebifierImplTest.java
core/src/test/java/com/backblaze/b2/client/B2TestHelpers.java
httpclient/src/main/java/com/backblaze/b2/client/webApiHttpClient/B2WebApiHttpClientImpl.java
samples/src/main/java/com/backblaze/b2/sample/B2Sample.java

https://github.com/Backblaze/b2-sdk-java/issues/28

---

core/src/main/java/com/backblaze/b2/client/B2StorageClientWebifierImpl.java
core/src/main/java/com/backblaze/b2/client/contentSources/B2Headers.java
core/src/main/java/com/backblaze/b2/util/B2StringUtil.java
core/src/test/java/com/backblaze/b2/client/B2LargeFileUploaderTest.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientWebifierImplTest.java
core/src/test/java/com/backblaze/b2/client/B2TestHelpers.java
core/src/test/java/com/backblaze/b2/client/contentSources/B2HeadersImplTest.java
core/src/test/java/com/backblaze/b2/util/B2StringUtilTest.java

Fix file name decoding in getFileInfoByName

---

core/src/main/java/com/backblaze/b2/json/B2JsonBigIntegerHandler.java
core/src/main/java/com/backblaze/b2/json/B2JsonHandlerMap.java
core/src/test/java/com/backblaze/b2/json/B2JsonTest.java

tested with updated unit tests.

b2json: support BigInteger in B2Json.

---

check_code
core/src/main/java/com/backblaze/b2/client/structures/B2ListBucketsRequest.java
core/src/main/java/com/backblaze/b2/client/structures/B2ListUnfinishedLargeFilesRequest.java
core/src/test/java/com/backblaze/b2/client/B2ListUnfinishedLargeFilesIterableTest.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientWebifierImplTest.java

The updated APIs just went live at Backblaze, so now it's time to put support into the SDK.

New params for b2_list_buckets and b2_list_unfinished_large_files

---

core/src/main/java/com/backblaze/b2/client/contentSources/B2ByteArrayContentSource.java
core/src/main/java/com/backblaze/b2/client/contentSources/B2ContentSource.java
core/src/main/java/com/backblaze/b2/client/contentSources/B2FileContentSource.java

"tested" that it still compiles with gradle locally.

javadocs: add some comments, prompted by azell's question in issue #50.

---

core/src/main/java/com/backblaze/b2/client/credentialsSources/B2CredentialsFromEnvironmentSource.java

Thanks mark for finding out the precondition was wrong.

Fixing bug for detecting System Env variable account ID

---

core/src/main/java/com/backblaze/b2/client/B2LargeFileStorer.java

This list is sorted, which will throw an exception if the list is Immutable

Copy the list of partStorers in case the list supplied is immutable.

---

core/src/main/java/com/backblaze/b2/json/B2JsonHandlerMap.java

This wasn't caught before by the tests because the `!inGetHandler` wasn't
tested in the case where the handler was already in the map.  Now, with
the precondition always tested, the tests caught it.
Testing: gradlew test

Fix bug with re-entrant call to getHandler()

---

check_code
core/src/main/java/com/backblaze/b2/client/B2StorageClientWebifierImpl.java
core/src/main/java/com/backblaze/b2/client/structures/B2DownloadByIdRequest.java
core/src/main/java/com/backblaze/b2/client/structures/B2DownloadByNameRequest.java
core/src/main/java/com/backblaze/b2/client/structures/B2GetDownloadAuthorizationRequest.java
core/src/main/java/com/backblaze/b2/client/structures/B2OverrideableHeaders.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientWebifierImplTest.java

These are specified in the requests to b2_get_download_authorization, b2_download_file_by_id, and b2_download_file_by_name

Adding support to override additional download headers.

---

core/src/main/java/com/backblaze/b2/client/structures/B2Capabilities.java
core/src/test/java/com/backblaze/b2/client/structures/B2ApplicationKeyTest.java

Add new 'listAllBucketNames' application key capability name to the B2Capabilities class.
Added a test to B2ApplicationKeyTest.

Add new 'listAllBucketNames' application key capability name.

---

core/src/main/java/com/backblaze/b2/client/structures/B2Capabilities.java
core/src/test/java/com/backblaze/b2/client/structures/B2ApplicationKeyTest.java

This adds the new readBuckets capability to the list of application key capabilities.
Added test in B2ApplicationKeyTest

Add new 'readBuckets' application key capability name.

---

core/src/test/java/com/backblaze/b2/client/B2ByteProgressFilteringListenerTest.java
core/src/test/java/com/backblaze/b2/client/B2ContentSourceWithByteProgressListenerTest.java
core/src/test/java/com/backblaze/b2/client/B2UploadProgressAdapterTest.java
core/src/test/java/com/backblaze/b2/client/B2UploadProgressUtilTest.java
core/src/test/java/com/backblaze/b2/client/structures/B2ApplicationKeyTest.java
core/src/test/java/com/backblaze/b2/client/structures/B2BucketTest.java
core/src/test/java/com/backblaze/b2/client/structures/B2ListUnfinishedLargeFilesRequestTest.java
core/src/test/java/com/backblaze/b2/client/structures/B2UploadProgressTest.java
core/src/test/java/com/backblaze/b2/json/B2JsonHandlerMapTest.java
core/src/test/java/com/backblaze/b2/util/B2BaseTest.java
core/src/test/java/com/backblaze/b2/util/B2InputStreamWithByteProgressListenerTest.java

This update includes the existing project license notice in the test files which had no license notice.

Correct missing license notices on the test files

---

core/src/main/java/com/backblaze/b2/json/B2JsonHandlerMap.java
core/src/test/java/com/backblaze/b2/json/B2JsonTest.java

(Note: TreeMap, which is a SortedMap, is used internally to store maps.)

added support for java.util.SortedMap interface.

---

.travis.yml

Set the python environment to 3.6

setting pyenv to 3.6

---

.travis.yml

Lets see if this builds

---

core/src/main/java/com/backblaze/b2/json/B2JsonObjectHandler.java
core/src/main/java/com/backblaze/b2/json/FieldInfo.java
core/src/test/java/com/backblaze/b2/json/B2JsonTest.java

replaced bits in a long with a bit set.
removed unnecessary bit set usage

support more than 64 fields per object.

---

.travis.yml

Should get our env how we need it

Should be using skip_cleanup to preserve our env.

---

.github/workflows/.ci_cd.yml

Please review and look at how the deploy is being done and that it should only happen for master.

Fix deploy

---

.github/workflows/deploy.yml
buildSrc/src/main/kotlin/b2sdk.gradle.kts

The bundle jars which are uploaded to GitHub include all of the
artifacts including the signing files with the artifacts.

Implement `createBundle` task in Gradle to create GitHub release bundle

---

CHANGELOG.md
gradle.properties

This PR updates the changelog and gradle.properties version.
Jira Ticket: [DEV-12985]
[DEV-12985]: https://backblaze.atlassian.net/browse/DEV-12985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update changelog and gradle.properties

---

gradle.properties

Updating gradle build number to release new version

DEV-23981: Update version number for release

---

CHANGELOG.md
gradle.properties

Update version to 6.2.1-SNAPSHOT

DEV-23981: Updating to SNAPSHOT
