Backblaze/b2-sdk-java

core/src/main/java/com/backblaze/b2/client/B2ByteProgressFilteringListener.java
core/src/main/java/com/backblaze/b2/client/B2RetryPolicy.java
core/src/main/java/com/backblaze/b2/client/B2Retryer.java
core/src/main/java/com/backblaze/b2/util/B2Clock.java
core/src/main/java/com/backblaze/b2/util/B2ClockImpl.java
core/src/main/java/com/backblaze/b2/util/B2ClockSim.java
core/src/main/java/com/backblaze/b2/util/B2DateTimeUtil.java
core/src/test/java/com/backblaze/b2/client/B2ByteProgressFilteringListenerTest.java
core/src/test/java/com/backblaze/b2/client/B2LargeFileUploaderTest.java
core/src/test/java/com/backblaze/b2/client/B2SleeperTest.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientImplTest.java
core/src/test/java/com/backblaze/b2/client/B2TestHelpers.java
core/src/test/java/com/backblaze/b2/util/B2ClockImplTest.java
core/src/test/java/com/backblaze/b2/util/B2ClockSimTest.java
core/src/test/java/com/backblaze/b2/util/B2DateTimeUtilTest.java

there's a real implementation -- B2ClockImpl.
there's a simulator -- B2ClockSim.
there are tests.
i haven't yet exercised or tested B2Clock.set() and get().
i suspect there'll be some tweaks there to handle updating
the clock in unit tests, since it's a global and i don't
currently allow it to be set more than once.

clock: add B2Clock to abstract time sources.

---

core/src/main/java/com/backblaze/b2/client/B2StorageClientWebifierImpl.java
core/src/main/java/com/backblaze/b2/util/B2StringUtil.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientWebifierImplTest.java
core/src/test/java/com/backblaze/b2/util/B2StringUtilTest.java

Also, update the percent-encoding to match the sample code
from the B2 web site.  It's not necessary to encode "/", and
file names read better when it's not encoded.
Testing:
- unit tests

Percent-encode files names when downloading by name.

---

core/src/main/java/com/backblaze/b2/client/B2LargeFileUploader.java

Marj noticed that I was incorrectly using the DefaultRetryPolicy when
I should've been using the retrySupplier to use the implementation
provided by the SDK user.

largeFileUploader: use retrySupplier more consistently.

---

core/src/main/java/com/backblaze/b2/json/B2Json.java
core/src/main/java/com/backblaze/b2/json/B2JsonWriter.java
core/src/test/java/com/backblaze/b2/json/B2JsonTest.java

as brianb phrased it "that's impolite".
since we think this is a bug fix, we're not bumping the major version number.

B2Json: toJson(...,outputStream) should *not* close the stream.

---

core/src/main/java/com/backblaze/b2/client/B2StorageClient.java
core/src/main/java/com/backblaze/b2/client/B2StorageClientImpl.java
core/src/main/java/com/backblaze/b2/client/B2UploadPartUrlCache.java
core/src/main/java/com/backblaze/b2/client/B2UploadUrlCache.java
core/src/main/java/com/backblaze/b2/client/structures/B2GetUploadPartUrlRequest.java
core/src/main/java/com/backblaze/b2/client/structures/B2GetUploadUrlRequest.java
core/src/test/java/com/backblaze/b2/client/B2LargeFileUploaderTest.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientImplTest.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientWebifierImplTest.java

using these directly is mostly discouraged because the SDK
handles lots of authentication and retry logic for you in
uploadSmallFile() and uploadLargeFile() and it won't do
that if you just get these upload urls directly and use
them outside its logic.
that said, they could be useful if you needed to give an
upload URL and authToken to some code that can't use the SDK.

b2StorageClient: add getUploadUrl() and getUploadPartUrl()

---

core/src/main/java/com/backblaze/b2/client/contentSources/B2Headers.java
core/src/main/java/com/backblaze/b2/util/B2StringUtil.java
core/src/test/java/com/backblaze/b2/client/contentSources/B2HeadersImplTest.java
core/src/test/java/com/backblaze/b2/util/B2StringUtilTest.java

i was using String.startsWith() to look headers whose name startsWith
"X-Bz-Info-" prefix.  however, headers are case-insensitive, so i needed
to change it to B2StringUtil.startsWithIgnoreCase.
of course, i had to implement startsWithIgnoreCase() and test it first.  :)
i also updated B2HeadersImplTest so it would fail without this fix, verified
it failed, and then applied the fix and verified it worked.
thanks to valenpo for running into this problem in one of his pull requests. :)
built & tested with "./gradlew build javadoc writeNewPom".
i also ran the sample.

B2Headers: fix extraction of fileInfos.

---

core/src/main/java/com/backblaze/b2/client/B2AccountAuthorizationCache.java
core/src/main/java/com/backblaze/b2/client/B2AccountAuthorizer.java
core/src/main/java/com/backblaze/b2/client/B2AccountAuthorizerSimpleImpl.java
core/src/main/java/com/backblaze/b2/client/B2StorageClient.java
core/src/main/java/com/backblaze/b2/client/B2StorageClientImpl.java
core/src/test/java/com/backblaze/b2/client/B2AccountAuthorizationCacheTest.java
core/src/test/java/com/backblaze/b2/client/B2ClientConfigTest.java
core/src/test/java/com/backblaze/b2/client/B2TestHelpers.java

We used to memorize the accountId passed into the AccountAuthorizer,
however that doesn't work when using applicationKeyId's to authenticate.
So in order for the SDK to work with the new Application Keys
we now store the accountId in the B2AccountAuthorizationCache after
successfully authorizing.
The changes were removing the B2Authorizer getAccount() method,
and calling getAccountId() from the cache, either with retries or not.
Updated Tests, passes All Tests in core and works with B2Sample.java
when pointed at staging where Application Key API's are turned on.
**ApplicationKeys are still not available in production.

These changes are in reference to application key work.

---

core/src/main/java/com/backblaze/b2/json/B2JsonUnionBaseHandler.java
core/src/test/java/com/backblaze/b2/json/B2JsonTest.java

tested with new unit test cases.
i'm not the B2Json expert, so I'll probably wait to merge this until brianb
can review it to see if i got it right and see if there are any cases i missed.

unions: support serializing objects containing unions.

---

.gitignore
core/src/main/java/com/backblaze/b2/json/B2Json.java
core/src/main/java/com/backblaze/b2/json/B2JsonObjectHandler.java
core/src/main/java/com/backblaze/b2/json/B2JsonOptions.java
core/src/main/java/com/backblaze/b2/json/FieldInfo.java
core/src/test/java/com/backblaze/b2/json/B2JsonTest.java

Adding @B2Json.sensitive annotation to fields to allow them to be redacted when outputting Json with the setRedactSensitive option on. The output is still valid JSON but no longer will conform to the structure specified, so this cannot be used to round-trip the JSON, however is useful when outputting structures to log files where certain information should not be exposed.

Adding the sensitive annotation

---

core/src/main/java/com/backblaze/b2/client/B2Sdk.java
core/src/main/java/com/backblaze/b2/client/B2StorageClientWebifierImpl.java
core/src/main/java/com/backblaze/b2/json/B2Json.java
core/src/test/java/com/backblaze/b2/client/B2ContentDetailsForUploadTest.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientWebifierImplTest.java
core/src/test/java/com/backblaze/b2/client/contentHandlers/B2ContentWriterTest.java
core/src/test/java/com/backblaze/b2/client/contentSources/B2ByteArrayContentSourceTest.java
core/src/test/java/com/backblaze/b2/util/B2InputStreamExcerptTest.java
core/src/test/java/com/backblaze/b2/util/B2Sha1AppenderInputStreamTest.java
core/src/test/java/com/backblaze/b2/util/B2Utf8UtilTest.java

To find them, I set a breakpoint in Charset.defaultCharset() and
ran the unit tests.  That found the cases I already knew about,
plus a bunch of other ones.
Testing: unit tests

Eliminate uses of the default charset by B2Json.

---

core/src/main/java/com/backblaze/b2/client/B2LargeFileUploader.java
core/src/main/java/com/backblaze/b2/client/contentSources/B2ContentSource.java
core/src/test/java/com/backblaze/b2/client/B2LargeFileUploaderTest.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientImplTest.java
samples/src/main/java/com/backblaze/b2/sample/UploadLargeFileFromUrl.java
samples/src/main/java/com/backblaze/b2/sample/UrlContentSource.java

This change teaches B2LargeFileUploader to ask B2ContentSource for
a B2ContentSource for a range of its content.  If the source returns
null (the default), we use the same B2PartOfContentSource to
"manually" excerpt, as we've always done.  The new way makes it more
reasonable to use a remote URL as the content source by making it possible
to do a range request on that URL instead of reading and discarding the
start of the URL multiple times.
testing:
* some additions to some unit tests.
i'm open to proposals for additional tests.
* exercised with the new UploadLargeFileFromUrl sample.

uploads: add optional B2ContentSource.createContentSourceWithRangeOrNull()

---

core/src/main/java/com/backblaze/b2/json/B2JsonHandlerMap.java
core/src/main/java/com/backblaze/b2/json/B2JsonInitializedTypeHandler.java
core/src/main/java/com/backblaze/b2/json/B2JsonNonUrlTypeHandler.java
core/src/main/java/com/backblaze/b2/json/B2JsonObjectHandler.java
core/src/main/java/com/backblaze/b2/json/B2JsonUnionBaseHandler.java
core/src/test/java/com/backblaze/b2/json/B2JsonTest.java

This fixes the bug where you could not use union types that were
recursive.  There's now a test case for this.
There was some confusing code to handle recursive object types that
put handlers in the map halfway through their constructors.  Giving
access to an object before it's constructed is bad practice, and
confusing.  Now, there are two phases of initialization: the constructor
and an initialize() method.  And the object doesn't leak out during
the constructor.  The B2JsonInitializedTypeHandler javadoc describes
the rules about what happens when.
This makes it clear what you cannot look at other handlers in your
constructor, and what fields you're allowed to look at in other
handlers in your initialize() method.
Testing: all tests

Split handler initialization into: constructor and initialize()

---

core/src/main/java/com/backblaze/b2/json/B2Json.java
core/src/main/java/com/backblaze/b2/json/B2JsonHandlerMap.java
core/src/main/java/com/backblaze/b2/json/B2JsonInitializedTypeHandler.java
core/src/main/java/com/backblaze/b2/json/B2JsonObjectHandler.java
core/src/main/java/com/backblaze/b2/json/B2JsonUnionBaseHandler.java
core/src/main/java/com/backblaze/b2/json/FieldInfo.java
core/src/test/java/com/backblaze/b2/json/B2JsonTest.java

#46
You can now provide a default value to use in a union when an unknown type is found.
Also, default values are now deserialized each time they are used, which is safer if the values are mutable.

Address issue #46, and improve default value handling

---

core/src/main/java/com/backblaze/b2/json/B2Json.java
core/src/main/java/com/backblaze/b2/json/B2JsonHandlerMap.java
core/src/main/java/com/backblaze/b2/json/B2JsonObjectHandler.java
core/src/main/java/com/backblaze/b2/json/B2JsonUnionBaseHandler.java
core/src/test/java/com/backblaze/b2/json/B2JsonTest.java

When the `B2JsonUnionBaseHandler` gets the handler for a field, it
needs to use the same logic that `B2JsonObjectHandler` uses to create
the handler for a field.
This worked before the change to allow recursive unions because the fields
were pulled from the object handlers, which had already been initialized
when the union was set up.  The union can no longer assume that, so it
needs to get the un-initialized the field handlers itself.
Testing: new unit test

Fix bug with Sets contained in unions.

---

core/src/main/java/com/backblaze/b2/json/B2JsonHandlerMap.java
core/src/test/java/com/backblaze/b2/json/B2JsonHandlerMapTest.java

If the initialize() method for a handler threw an exception, the
handler was not initialized, but the getHandler() method left it
in the map.  There's now a test for that case, and some cleanup
code to remove handlers from the map if there's an error.
Also, add a test for HashSet being disallowed.
Testing: unit tests

Fix bug that can leave an uninitialized handler in the map.

---

core/src/main/java/com/backblaze/b2/json/B2JsonCharSquenceHandler.java
core/src/main/java/com/backblaze/b2/json/B2JsonHandlerMap.java
core/src/main/java/com/backblaze/b2/json/B2JsonWriter.java
core/src/main/java/com/backblaze/b2/util/B2Utf8Util.java
core/src/test/java/com/backblaze/b2/json/B2JsonTest.java

Deserialization will still create a String. It is a future area of optimization if we want to support allocation free parsing in B2Json.

Adding support to B2Json for CharSequence

---

core/src/main/java/com/backblaze/b2/json/B2Json.java
core/src/main/java/com/backblaze/b2/json/B2JsonObjectHandler.java
core/src/main/java/com/backblaze/b2/json/FieldInfo.java
core/src/test/java/com/backblaze/b2/json/B2JsonTest.java

Adding omitNull parameter to the @B2Json.optional annotation to not serialize fields that have a null value. This is false by default.

Adding an omitNull parameter to @B2Json.optional

---

core/src/main/java/com/backblaze/b2/client/structures/B2ListFileVersionsRequest.java
core/src/test/java/com/backblaze/b2/client/B2ListFileVersionsIterableTest.java

when "folders" are allowed to be returned from b2_list_file_versions,
sometimes we need to start queries from "folders", which have a fileName
but no fileId.  this means we can't require startFileId to be null.
thanks for hitting and reporting this, mark!  :)
i also let IDEA simplify some assertions in the corresponding test.
but in some places i prefer "assertTrue(!blah)" over "assertFalse(blah)",
especially in a long list of other assertions where it's harder to see
it's an "assertFALSE".
testing:
* ./gradlew build javadoc writeNewPom

B2ListFileVersionsRequest: remove overzealous assert

---

CHANGELOG.md
httpclient/build.gradle
httpclient/src/main/java/com/backblaze/b2/client/webApiHttpClient/HttpClientFactoryImpl.java

By default, HttpClient will normalize URIs, which includes replacing double slashes (`//`) with a single slash. This will alter the request URI and implicitly change the name of files requested through the DownloadByName API where the filename is part of the URI. We need to disable this normalization to allow filename requests to go through as-is.
Updating the HttpClient version to 4.5.9 which is the first version that the setNormalizeUri option became available.

Disable URI normalization in Apache HttpClient

---

check_code
core/src/main/java/com/backblaze/b2/client/B2StorageClientWebifierImpl.java
core/src/main/java/com/backblaze/b2/client/contentSources/B2Headers.java
core/src/main/java/com/backblaze/b2/client/structures/B2FileVersion.java
core/src/main/java/com/backblaze/b2/client/structures/B2Part.java
core/src/main/java/com/backblaze/b2/util/B2Md5.java
core/src/test/java/com/backblaze/b2/client/B2AlreadyStoredPartStorerTest.java
core/src/test/java/com/backblaze/b2/client/B2CopyingPartStorerTest.java
core/src/test/java/com/backblaze/b2/client/B2LargeFileStorerTest.java
core/src/test/java/com/backblaze/b2/client/B2LargeFileUploaderTest.java
core/src/test/java/com/backblaze/b2/client/B2ListPartsIterableImplTest.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientImplTest.java
core/src/test/java/com/backblaze/b2/client/B2TestHelpers.java
core/src/test/java/com/backblaze/b2/client/B2UploadingPartStorerTest.java
core/src/test/java/com/backblaze/b2/client/structures/B2FileVersionTest.java
core/src/test/java/com/backblaze/b2/client/structures/B2PartTest.java

B2 will soon be returning these fields, and it will be good to let
client code see them.  The first code that needs them will be internal
Backblaze tests that exercise the B2 APIs.
B2Headers now has a getContentMd5() method, which reads the "Content-MD5"
header that will be returned when downloading a file.  This header is
also used when getting file info by name; the info is returned in the
headers from a HEAD request on the file.
Testing: All Tests

Extend B2FileVersion and B2Part to include contentMd5.

---

core/src/main/java/com/backblaze/b2/client/B2StorageClientWebifierImpl.java
core/src/main/java/com/backblaze/b2/client/contentSources/B2Headers.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientWebifierImplTest.java

Both Apache HttpClient and okhttp support 100-continue, so it is safe to blindly add the header to the requests.

Add the "Expect: 100-continue" header to upload file/part requests.

---

core/src/main/java/com/backblaze/b2/json/B2Json.java
core/src/main/java/com/backblaze/b2/json/B2JsonHandlerMap.java
core/src/test/java/com/backblaze/b2/json/B2JsonTest.java

This allows the user to supply type information to aid in `B2JsonTypeHandler` resolution for the top-level object. If the type information is not supplied, `B2Json` falls back to the existing behavior of resolving by class.
The first commit is a small refactor.
Second is the feature.
Third is a test.

B2Json: Allow generic types for top-level objects from select entry points

---

CHANGELOG.md
core/src/main/java/com/backblaze/b2/client/B2StorageClientWebifierImpl.java
core/src/main/java/com/backblaze/b2/client/contentSources/B2Headers.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientWebifierImplTest.java
core/src/test/java/com/backblaze/b2/client/B2TestHelpers.java

This PR validates against all supported chars in RFC 7230 https://tools.ietf.org/html/rfc7230#section-3.2
Testing: All tests

validate chars in file info header name

---

check_code
common.gradle

This update fixes the check_code python script so its default parameters work when executing it directly in-place like this:
./check_code
Also updates the common.gradle script to pass the desired path name based on its current working directory of `./core` and to successfully read the version.txt file when used from the ./samples/build.gradle script.

Fixes for the check_code python script and samples gradle file

---

core/src/main/java/com/backblaze/b2/json/B2JsonHandlerMap.java
core/src/test/java/com/backblaze/b2/json/B2JsonTest.java

The work I did back in December didn't handle the case when a parameterized class had a member array whose type was a parameter and this PR addresses that.

Add support for parameterized classes that contain generic arrays.

---

check_code

This regular expression has an unescaped `.`, so it might match more hosts than expected. For example, this lines below will show LGTM.
```python
######################################################################
#
#
#
#
######################################################################
```
```bash
> ./check_code check_code
check_code: looks good.
```

Fix regular expression that has an unescaped

---

CHANGELOG.md
core/src/main/java/com/backblaze/b2/client/B2AlreadyStoredPartStorer.java
core/src/main/java/com/backblaze/b2/client/B2CancellableContentSource.java
core/src/main/java/com/backblaze/b2/client/B2CancellationToken.java
core/src/main/java/com/backblaze/b2/client/B2CopyingPartStorer.java
core/src/main/java/com/backblaze/b2/client/B2LargeFileStorer.java
core/src/main/java/com/backblaze/b2/client/B2PartStorer.java
core/src/main/java/com/backblaze/b2/client/B2StorageClient.java
core/src/main/java/com/backblaze/b2/client/B2StorageClientImpl.java
core/src/main/java/com/backblaze/b2/client/B2UploadingPartStorer.java
core/src/test/java/com/backblaze/b2/client/B2AlreadyStoredPartStorerTest.java
core/src/test/java/com/backblaze/b2/client/B2CancellableContentSourceTest.java
core/src/test/java/com/backblaze/b2/client/B2CancellationTokenTest.java
core/src/test/java/com/backblaze/b2/client/B2CopyingPartStorerTest.java
core/src/test/java/com/backblaze/b2/client/B2LargeFileStorerTest.java
core/src/test/java/com/backblaze/b2/client/B2UploadingPartStorerTest.java

This behaves like `storeLargeFileFromLocalContent` but returns a cancellable future which will prevent additional tasks from starting and attempt to cancel in-progress API calls.
Addresses #16

Adding storeLargeFileFromLocalContentAsync method to B2StorageClient

---

.travis.yml

Following suggestion from b2 sdk python team, upgrade setuptools and pip prior to installing B2 CLI instead of calling `pip3 install "setuptools_scm[toml]<6.0"`
Jira: https://backblaze.atlassian.net/browse/DEV-8602

upgrade setuptools and pip before installing B2 CLI

---

core/src/main/java/com/backblaze/b2/client/B2StorageClient.java
core/src/test/java/com/backblaze/b2/client/B2StorageClientImplTest.java

The default implementation B2StorageClient::getBucketOrNullByName() fails if the app key capability only has listBuckets capability for a single bucket because it uses listBuckets() and then iterates through all the bucket names. Needs to be changed to instead use B2ListBucketsRequest to specify the bucket name.
Reported in #151
Testing: unit tests

change getBucketOrNullByName to request specific bucket by name

---

core/src/main/java/com/backblaze/b2/client/B2StorageClient.java

Simple documentation fix in B2StorageClient.

fix copy/paste typo in Javadoc for B2StorageClient.fileNames(bucketId)

---

CHANGELOG.md
httpclient/src/main/java/com/backblaze/b2/client/webApiHttpClient/B2WebApiHttpClientImpl.java
httpclient/src/test/java/com/backblaze/b2/client/webApiHttpClient/B2WebApiHttpClientImplTest.java

If the error text is not of type `B2ErrorStructure`, then attempt to return a subtype of B2Exception. Returning a B2Exception subtype enables the `B2Retryer` to retry calls that may succeed on retry.

Updates B2WebApiHttpClientImpl to return a subtype of B2Exception on error
